### ISSUE TITLE
Add eyelight shader and use it as default

### ISSUE THREAD

**Issue by lachsen** [xml3d/xml3d.js#1]
I think an eyelight shader as default shader would be nice. 
It makes the 3D shape more recognizable than simple flat shading or phong shading without light sources.
This is especially useful for first steps with XML3D.

**Comment by ksons** [comment]
As dicussed, we won't use eyelight shader due to its integrated light which does not appear in the scene description. Instead we'll add another useful defualt shader (instead of error shader as it is right now).

**Comment by csvurt** [comment]
This issue has been subsumed under #109
