### ISSUE TITLE
Xflow: No operator with name 'xflow.add' found

### ISSUE THREAD

**Issue by j4yk** [xml3d/xml3d.js#100]
Xflow tells me that xflow.add could not be found (the issue title is the error message from the console) and I have no clue why. Below is a subset of my code which triggers this error (verified by removing everything else except html boilerplate). What could possibly cause this?

        <script src="http://www.xml3d.org/xml3d/script/xml3d.js" type="text/javascript"></script>
        <script src="http://www.xml3d.org/xml3d/script/tools/camera.js" type="text/javascript"></script>
        
            <dataflow id="createBoxesFromPointCloud" out="position">
				<float3 param="true" name="center"></float3>
				<float3 param="true" name="extent"></float3>
				<compute>
					position = xflow.add(center, extent);
				</compute>
            </dataflow>
            <mesh type="tristrips" style="shader: #boxInstancesShader">
                <data compute="dataflow['#createBoxesFromPointCloud']">
                    <float3 name="center">0 0 0 0.463232 0.005 0.49296 ...</float3>
                    <float3 name="extent">1 0.005 1 0.0374403 0.005 0.0130795 ...</float3>
                </data>
            </mesh>

PS. is there another active channel for questions about XML3D/Xflow that are not possibly bug reports or feature requests but rather calls for help? :-)

**Comment by csvurt** [comment]
Well it looks like the xflow.add operator didn't make it into the last release build, which is interesting... 

We're in the process of moving to a better build system right now so I'll leave this issue open until that's ready (release 4.9) to make sure this doesn't happen again. Until then you could register the operator yourself, [just throw this into a .js file](http://pastebin.com/bW3d6b8v) and include it after xml3d.js.

We have a public mailing list for questions and discussion and calls for help [available here.](https://mail.cg.uni-saarland.de/cgi-bin/mailman/listinfo/xml3d-public) I'd like to get some forums up at some point but until then that's your best bet.

**Comment by csvurt** [comment]
I've double checked to make sure all the operators were included this time around, everything looks ok so I'll close this now.
