### ISSUE TITLE
getElementByPoint inverted normals

### ISSUE THREAD

**Issue by l337r007** [xml3d/xml3d.js#112]
Sometimes, getElementByPoint returns inverted normals, where one component of the vector has a negative sign compared to the expected normal vector. I'll try to come up with a scenario where I can consistently reproduce that behaviour.

**Comment by csvurt** [comment]
I discovered a bug with my own test scene that was causing a normal of -1,-1,-1 to sometimes be returned. I'm not sure if this was causing your problem but maybe you could have a look again with this fix.

I couldn't find any other problems in my test scene so if it's still broken a test case from yourself would be helpful.

**Comment by l337r007** [comment]
Thanks for looking into this. I'll see if I can get your patch applied to the XML3D.js version we're using. The issue is a bit on the back burner for us right now as we're doing other things again.

**Comment by csvurt** [comment]
Closing this for now, if it shows up again feel free to reopen the issue.
