### ISSUE TITLE
Externalizing Xflow operators does not work

### ISSUE THREAD

**Issue by stlemme** [xml3d/xml3d.js#113]
While moving script elements with Xflow operators from html to external xml asset, it results in following error messages:

Xflow: No operator 'xflow.quads2triangles' with matching type signature found:
xflow.quads2triangles(float3 undefined)
	 * For 1. argument 'undefined': DataEntry 'position' does not exist External Document: http://localhost/projects/xml3d-experimental/text/text.xml

Example provided at https://github.com/stlemme/xml3d-experimental/tree/external-xflow-operator/text
The base version of the master branch works quite well.

**Comment by ksons** [comment]
Did I understand correctly that this issue only occurs on the development branch?

**Comment by stlemme** [comment]
Indeed, the example uses a dev-build. Actually, I did not tested the latest stable version.

**Comment by stlemme** [comment]
The issue re-appeared in a different fashion (no error message at all, sporadically it does work).
I suggest to reopen this issue.
Please find an example at https://github.com/stlemme/xml3d-experimental/tree/master/geometry showcasing the issue.

**Comment by csvurt** [comment]
The fix for this will be included in the upcoming 4.9.4 hotfix, until then you can find it on the hotfix-4.9.4 branch. The example seems to work consistently now, let me know if you run into any other problems!
