### ISSUE TITLE
Custom Marker for AR

### ISSUE THREAD

**Issue by shawn-northrop** [xml3d/xml3d.js#119]
Is it possible to create Custom Markers and use them for an Augmented Reality implementation?

**Comment by csvurt** [comment]
Yes, we actually have a couple of examples based on marker tracking, you can find them [here](http://xml3d.github.io/xml3d-examples/examples/xflowAR/ar_simple_no_flip.html) and [here](http://xml3d.github.io/xml3d-examples/examples/xflowAR/ar_flying_teapot.html). They use the [JSARToolkit](https://github.com/kig/JSARToolKit) and some custom Xflow operators to produce transformation matrices from the marker tracking information. 

Those examples also show how to use a webcam as input for the marker detection process.
