### ISSUE TITLE
Unhandled value changed event in view adapter for attribute:fieldofview

### ISSUE THREAD

**Issue by simpae** [xml3d/xml3d.js#121]
Changing the fieldOfView parameter either using ````viewNode.setAttribute('fieldofview', 0.9);```` or using ````viewNode.fieldOfView = 0.9;```` yields the following warning:
> Unhandled value changed event in view adapter for attribute:fieldofview

Setting ````fieldofview```` in the .html document works as expected.

**Comment by csvurt** [comment]
Confirmed on 4.9.1. Apparently none of the tests we have for this checked the internal state of the renderer, only the state of the attribute and field on the element.

I've pushed a fix to the develop branch, we'll do a bugfix release later this week after we've added regression tests. Until then you could use the [development build.](http://xml3d.org/xml3d/scripts/xml3d-dev.js)

Thanks for the report!
