### ISSUE TITLE
Quickstart guides miss a mention that src requests usually fail when running scenes from filesystem

### ISSUE THREAD

**Issue by tospie** [xml3d/xml3d.js#124]
xml3d.js retrieves linked resources for meshes, models, shaders and such via ajax requests. These requests fail in particular when trying to run an XML3D scene from the local file system, instead of starting it from a server.

For beginners, uploading the scene to some web server seems to be no natural step. The need to do so should be put prominently at the beginning of the quick start guides, especially as the simple teapot example from the Wiki already fails, if not doing so.

**Comment by csvurt** [comment]
I've added info about using XML3D locally to both the [Getting Started](https://github.com/xml3d/xml3d.js/wiki/Getting-started) and [Basics of XML3D](https://github.com/xml3d/xml3d.js/wiki/The-Basics-of-XML3D) sections in the Wiki. 

We should still output a warning if XML3D encounters any local filesystem paths. This should be scheduled as part of the resource manager overhaul in 5.1

**Comment by csvurt** [comment]
Trying to reference resources from a filesystem should now throw an error with a link to a Help issue with more information.
