### ISSUE TITLE
package.json: Do dependencies need to be "master"?

### ISSUE THREAD

**Issue by l337r007** [xml3d/xml3d.js#130]
I'd like to use xml3d as an npm dependency, and was wondering whether you absolutely need to depend on the `master` branches of `gl-matrix` and `texture-manager`, rather than a specific version. Especially since `gl-matrix` is on npm proper.
For `texture-manager`, wouldn't the `<URL>#<commitish>` syntax for dependencies be more appropriate?

**Comment by ksons** [comment]
6584825834252dff16373c1d801c9df4cdeb1bdf fixes this for gl-matrix.

**Comment by csvurt** [comment]
Fixed for the texture-manager in the 5.2 release
