### ISSUE TITLE
XML3D does not initialize when adding xml3d tag as part of hierarchy 

### ISSUE THREAD

**Issue by l337r007** [xml3d/xml3d.js#132]
When adding a structure such as
```
<div>
 <xml3d>
   <!--- more stuff -->
 </xml3d>
</div>
```
to the DOM (using, e.g. `appendChild`), the MutationRecord's `addedNodes` list only contains the toplevel `<div>`. Since xml3d.js only checks the nodes in the list, the newly added xml3d tag is missed, and nothing is initialized.

**Comment by csvurt** [comment]
I'll add this to the upcoming 4.9.3 hotfix
