### ISSUE TITLE
camera.js broken on iOS devices

### ISSUE THREAD

**Issue by ksons** [xml3d/xml3d.js#133]
Issue from mailing list. Needs to be confirmed.

**Comment by csvurt** [comment]
Confirmed with Safari on iOS8. I'll see if I can rustle up an Apple development machine to take a closer look.

**Comment by csvurt** [comment]
Turns out this was an issue in our touch event handler in xml3d.js. I've tested this fix with Android Chrome, Android Firefox, iOS 8 Safari and iOS 8 Chrome and they all seem to work properly with camera.js now. 

I'll roll this out to v4.9 with the next hotfix and it'll of course be in 5.0 too.
