### ISSUE TITLE
tools/camera.js messes up slider behaviour for input type="range"

### ISSUE THREAD

**Issue by fnunnari** [xml3d/xml3d.js#139]
Hi there,

When using the camera.js, to navigate the scene using the mouse, an input selector of type "range" doesn't work properly anymore.
Once clicked, the slider remains "attached" to the mouse pointer and doesn't loose the focus. Not even when clicking outside or pressing tab.

To me, looks like the xml3d canvas is "eating up" the mouse-released event that would unlock the slider.

Happens in Chrome Version 44.0.2403.130 (64-bit), Firefox 39.0, and Opera 31.0.1889.99.
Mac OS X 10.9.5 64-bit.

The following code reproduce the problem. Comment out the inclusion of camera.js and the slider will behave correctly.

&lt;!doctype html&gt;
&lt;html&gt;
  &lt;head&gt;
    &lt;title&gt;XML3D Boilerplate Code&lt;/title&gt;
    &lt;!-- Include the xml3d.js library first --&gt;
    &lt;script type=&quot;text/javascript&quot; src=&quot;http://www.xml3d.org/xml3d/script/xml3d.js&quot; &gt; &lt;/script&gt;
    &lt;!-- COMMENT OUT THE FOLLOWING LINE (CAMERA.JS) AND THE SLIDER WILL BEHAVE CORRECTLY --&gt;
    &lt;script type=&quot;text/javascript&quot; src=&quot;http://www.xml3d.org/xml3d/script/tools/camera.js&quot; &gt; &lt;/script&gt;
    &lt;!-- Other &lt;script&gt; tags --&gt;
    &lt;script type=&quot;text/javascript&quot;&gt;
      function setAnimationKeyframe(kf) {
        console.log(&quot;Animation KF: &quot;+kf)
      }
    &lt;/script&gt;
  &lt;/head&gt;
  &lt;body&gt;
    &lt;!-- You can place an xml3d element anywhere inside &lt;body&gt;.
      Currently we only support inline style properties to style the xml3d element --&gt;
    &lt;xml3d style=&quot;width: 600px; height: 400px;&quot; activeView=&quot;#currentView&quot; &gt;
      &lt;!-- The view element determines the camera position of the 3D scene. 
        When using multiple &lt;view&gt; element, you can select one view by document id via the activeView attribute of &lt;xml3d&gt; --&gt;
      &lt;view id=&quot;currentView&quot; position=&quot;0 0 50&quot;&gt;&lt;/view&gt;
    &lt;/xml3d&gt;
    Keyframe number: &lt;input type=&quot;range&quot; min=&quot;1&quot; value=&quot;1&quot; max=&quot;25&quot; step=&quot;1&quot; oninput=&quot;setAnimationKeyframe(event.target.value);&quot;&gt; 
  &lt;/body&gt;
&lt;/html&gt;

**Comment by csvurt** [comment]
The standard camera is getting a major overhaul in 5.0, I've pulled the relevant fixes over to our 4.9.4 hotfix branch. The hotfix will probably go out next week until then you could checkout camera.js from hotfix-4.9.4 it seems to work fine with your example scene now.

Thanks for the report!
