### ISSUE TITLE
Memory leak in asset overwrites

### ISSUE THREAD

**Issue by stlemme** [xml3d/xml3d.js#142]
When frequently adding and removing assets together with overwriting asset properties, a memory leak appears that grows rather fast.

An example showcasing this issue is available at https://stlemme.github.io/xml3d-experimental/memory-leak/memory-benchmark-test.html (caution!)

**Comment by csvurt** [comment]
I've tracked this down to the way dataflows inside assets are disposed (or rather aren't). The substitution nodes are never removed so you eventually end up with thousands of mesh data buffers.

I'll work on a fix for this for v4.9.4

**Comment by csvurt** [comment]
A bunch of fixes just made their way onto the master branch as part of the 4.9.4 release. The test scene you provided stays at a nice ~50 mb for me now!

I'll close this now, if you run into any other leaks feel free to open it up again.
