### ISSUE TITLE
Xflow: time data source

### ISSUE THREAD

**Issue by l337r007** [xml3d/xml3d.js#15]
Another feature request, this time for xflow. An operator yielding time would be very neat, so I could do
```
<data compute="transform = xflow.createTransform(translation, rotation)">
    <data compute="animationKey = xflow.time() % 10.0" />
    <float4 key="0.0" name="rotation">0.0 0.0 0.0 1.0</float4>
    <data compute="translation = xflow.lerpSeq(translation, animationKey)">
        <float3 key="0.0" name="translation">0.0 0.0 0.0</float3>
        <float3 key="5.0" name="translation">0.0 100.0 0.0</float3>
        <float3 key="10.0" name="translation">0.0 0.0 0.0</float3>
    </data>
</data>
```
where the resulting transform would repeatedly move 100 units along the y-axis up and down in 10 seconds time.
This is similar in usage to [Quartz Composer's Patch Time](http://quartzcomposer.com/patches/101-patch-time).
Note that I have blindly assumed the existence of a modulo (`%`) operator and possibly abused the syntax due to lack of documentation ;)
PS: I have a ton more of these, maybe it wold be easier to document how to write new operators?

**Comment by csvurt** [comment]
I'm going to go ahead and close this 2 years later. The 5.0 release will include a section in the spec on how to write custom operators and the same functionality can be achieved by controlling the animation keys through Javascript at the page level.
