### ISSUE TITLE
Animation bug: armature modifies only root bone position

### ISSUE THREAD

**Issue by Arsakes** [xml3d/xml3d.js#150]
I've used blender exporter to create an animated asset - it works perfectly if there is only one bone with 1.0 weight for whole asset. 
However for skeleton that consists of many bones and different weights the animations doesn't work as expected (or rather as in blender). The situation is following:
1. All files load correctly there are no errors related to file structure.
2  The only effect that armature has on object is translation of whole mesh (it looks like only position for root  bone was computed and effects applied to mesh) there are no other deformation whatsoever. Despite the fact almost all bones have non-zero rotation and position changes.

I'm eager to give you both xml3d assets and blender file to test.

**Comment by ksons** [comment]
Since this seems to be a blender exporter related issue, I'll move it over to https://github.com/ksons/xml3d-blender-exporter

**Comment by ksons** [comment]
This issue was moved to ksons/xml3d-blender-exporter#14
