### ISSUE TITLE
View not changing

### ISSUE THREAD

**Issue by wheybags** [xml3d/xml3d.js#154]
Hey, currently <view> tags are not fuctioning as expected, (or, as described in the tutorial: https://github.com/xml3d/xml3d.js/wiki/The-Basics-of-XML3D )

With the following html:

```html
<html>
    <head>
        <script src="../build/output/xml3d.js"></script>
        <script src="../tools/camera.js"></script>
    </head>
    <body>
        <xml3d>
            <view position="0 0 100"></view>
            <mesh src="teapot.json"></mesh>
        </xml3d>
    </body>
</html>
```

I expect to get:
![image](https://cloud.githubusercontent.com/assets/1093274/10698966/7d566204-79ab-11e5-9717-6bee51cc5d14.png)

, but what I get is the view from the default position at the origin:
![image](https://cloud.githubusercontent.com/assets/1093274/10698977/8dcca24c-79ab-11e5-80d6-a00d5d551daa.png)

(screenshots taken from the tutorial page I linked earlier)

Also, the camera controller doesn't work.

It works in the 4.9.5 tag.
Using bisect, the first bad commit for the view tag not functioning is 51caae628c0c0d45e8a3ca64722d1682f096bea6, so ping @ksons

**Comment by wheybags** [comment]
6e17a1f66d6f5b08462353ad4aa052a953b7df72 is the first bad commit for the camera not working (I think, it just has a bunch of errors in console and nothing rendered), ping @csvurt

**Comment by wheybags** [comment]
Ugh, my bisects are probably inaccurate because of commits that just error out on anything, but you get the gist of it.
There are commits where the views position attribute is being applied but the camera doesn't work

**Comment by csvurt** [comment]
Oh balls, I forgot to update the tutorials to 5.0. I'll get on that first thing on Monday, until then you'll want to use a transform with the view element instead:

```
<view style="transform: translate3d(0, 0, 100px);"></view>

or 

<transform id="cameraTransform" translation="0 0 100"></view>
<view transform="#cameraTransform"></view>
```

Sorry for the confusion :S

**Comment by csvurt** [comment]
Ok, the wiki pages and tutorials should be up to date now. Thanks again for the heads up!
