### ISSUE TITLE
Sliders don't work with xml3d camera.js

### ISSUE THREAD

**Issue by Arsakes** [xml3d/xml3d.js#159]
The fact that camera.js (tool script that goes with git version of xml) attaches _mousemove_ and _mouseclick_ handlers to the _document_ make it impossible to use sliders (`<input type="range">`).

**Comment by csvurt** [comment]
Yeah it looks like a check was lost in a merge conflict, these events are being stopped when they shouldn't be. I'll take a look today and see if I can improve the event logic a bit, I think this is the second time we've had a problem with these things...
