### ISSUE TITLE
My browser doesn't support XML3D. What to do?

### ISSUE THREAD

**Issue by l337r007** [xml3d/xml3d.js#16]
The error message tells me to "Please visit http://www.xml3d.org to get information about browsers supporting XML3D."
However, [a search on xml3d.org for "Browser"](http://xml3d.org/?s=Browser) reveals little to no information.
The error message should be more informative and/or there should be a dedicated link that leads to a browser compatibility page.

**Comment by csvurt** [comment]
Instead of linking to the Github wiki page directly I've created a new redirect at xml3d.org/help. This should be a stable link that won't change in the future even if the redirect does.
