### ISSUE TITLE
Error when changing CSS transform on light elements

### ISSUE THREAD

**Issue by csvurt** [xml3d/xml3d.js#163]
Changing the CSS transform of a ```<light>``` element through the ```style``` attribute throws an error ```RenderLight::setLocalMatrix not implemented```. This error is not thrown during the initial scene construction, so either the CSS transform is completely ignored there or it's implemented through a different code path. We should make sure it's consistent either way.

Also make sure we have tests that cover changing CSS transforms for all transformable elements.

**Comment by Arsakes** [comment]
It seems the same happens if you refer transform id. Just checked it
I generate following code:
`<light transform="#t-c26" model="urn:xml3d:light:point" style="display: inline;"><float3 name="intensity">1 1 1</float3><float3 name="attenuation">0 0 0.05</float3></light>`

**Comment by Arsakes** [comment]
The same happens using transform=#id on light (after initalization).
