### ISSUE TITLE
camera options from 

### ISSUE THREAD

**Issue by PolGuixe** [xml3d/xml3d.js#165]
Can the camera mode be changed from an xml tag?

**Comment by csvurt** [comment]
If you mean the "fly" and "examine" modes then no, these are part of the camera.js plugin and are controlled through Javascript:

```javascript
var camera  = new XML3D.StandardCamera(viewElement);
...
camera.mode = "fly";
```

Some of the view parameters can be changed through HTML elements though, as described in the [predefined view models](http://xml3d.org/xml3d/specification/5.0/#predefined-view-models) and [view element](http://xml3d.org/xml3d/specification/5.0/#the-view-element) sections in the spec.
