### ISSUE TITLE
"No FormatHandler could be found" errors

### ISSUE THREAD

**Issue by telethonic** [xml3d/xml3d.js#168]
Hello,

For XML model files that previously worked fine I'm suddenly seeing this error:

"TypeError: No FormatHandler could be found for the document http://localhost/test/basic.xml"

Was there a change, or is there something obvious I'm missing?

Also, if the issue tracker is not the right venue for these types of reports, please let me know.

Thanks.

**Comment by telethonic** [comment]
Update: replacing the script http://www.xml3d.org/xml3d/script/xml3d.js with a version
that I pulled a few weeks ago made the error disappear :(

**Comment by csvurt** [comment]
Yeah we made some changes to the way resources are loaded in the 5.1 release, a colleague here is having the same problem. It must be related to the way some HTTP servers deliver .xml files.

I'll take a look at this today and hopefully push a fix, in the mean time just stick to http://www.xml3d.org/xml3d/script/xml3d-5.0.js ;)

Thanks for the report! This is definitely the right place for bugs.

**Comment by ksons** [comment]
Hi,

the new FormatHandler accepts XML files with Content-Type ```application/xml``` only. Some HTTP servers stills deliver XML files with ```text/xml```.

I had the same issue and committed a fix to develop: 9bcd6d04eaae1eb523472cbae9235dc9ef4d3f1e

**Comment by telethonic** [comment]
Thanks :)

**Comment by csvurt** [comment]
Just updated the scripts with a hotfix for this so you should be able to use http://www.xml3d.org/xml3d/script/xml3d.js again ;)

**Comment by telethonic** [comment]
Just checked, and yes, it works again.

From now on I'll load local copies to be on the safe side..

**Comment by csvurt** [comment]
Or link to a specific version like http://www.xml3d.org/xml3d/script/xml3d-5.1.1.js. Any version with 3 numbers like that (a.b.c) won't ever change again once it's uploaded.
