### ISSUE TITLE
initXML3DElement() has to check if the element is still a member of the DOM 

### ISSUE THREAD

**Issue by afrische** [xml3d/xml3d.js#169]
Consider the following:
 1. a xml3d element is added and directly removed, e.g. in a qunit fixture
 2. the MutationObserver will fire and eventually initXML3DElement() will be called on the added nodes
 3. the element has no longer a parent and an exception will be thrown 

hth
Andreas

**Comment by csvurt** [comment]
Thanks for the report, I'll schedule this for the next hotfix.
