### ISSUE TITLE
Mesh Error: Cannot read property '_removeSubstitutionNode' of undefined

### ISSUE THREAD

**Issue by stlemme** [xml3d/xml3d.js#177]
Full error message:
Mesh Error: Cannot read property '_removeSubstitutionNode' of undefined <mesh id=​"sphere">​…​</mesh> @ xml3d-5.1.1.js:20578

XML3D version 5.0.4 works, 5.1.0 introduces Exception, newer fail with Mesh Error as above

```
<mesh id="sphere">
	<data compute="dataflow['http://xml3d.github.io/xflow-registry/dataflow/geometry.xml#gen-sphere']">
		<int name="segments">8 6</int>
		<float name="phi">0 1</float>
		<float name="theta">0 1</float>
	</data>
</mesh>
```

**Comment by csvurt** [comment]
Yup, this error is being thrown in the tests for external operators too (tests still go through though). Probably has to do with the cleanup of unused resources that was introduced with the resource manager changes in 5.1.
