### ISSUE TITLE
Normal mapping

### ISSUE THREAD

**Issue by Arsakes** [xml3d/xml3d.js#184]
Hi, 
is there any utility that will help me with computing tangent/bitangent vectors for model?
I want to implement normal mapping - this seem to be only difficulty.

It would be perfect is XML3D could generate them.

**Comment by csvurt** [comment]
Hi,
here's an Xflow operator that generates tangent vectors:

http://xml3d.org/xml3d/shade-studio/external/script/calculateTangents.js

```html
<data compute="tangent = xflow.calculateTangents(index, normal, texcoord)">
   <!-- Mesh data containing index, positions, normal, texcoord -->
</data>
```
