### ISSUE TITLE
camera.js prevents some events from firing

### ISSUE THREAD

**Issue by simpae** [xml3d/xml3d.js#19]
While using <code>http://www.xml3d.org/xml3d/script/tools/camera.js</code> as a camera controller some events seem to be prevented from firing when using Chrome. This behaviour did not occur when using Firefox.

In my case I was attaching a change event to a listbox which only fired when dragging to select an option, not when simply clicking on an option.

I was able to track this behaviour down to lines 190 & 191 where mouse events are attached to the document.
Replacing <code>document.</code> with <code>this.canvas.</code> in lines 190 & 191 fixed the problem.
This however prevents the camera from being rotated when the mouse leaves the canvas :)

**Comment by csvurt** [comment]
This should be fixed in cb601b2fb7606d6dde7a873f76e80f2bfb11da09 which will land in the upcoming 4.9.4 hotfix.
