### ISSUE TITLE
Loading textures for postprocessing shaders

### ISSUE THREAD

**Issue by Arsakes** [xml3d/xml3d.js#190]
Does XML3D provides some interface for loading textures for postprocessing shaders (ones which are not associated with `<mesh>`es or `<model>`s ?

**Comment by csvurt** [comment]
Not right now, you'd have to either load and create the textures manually in Javascript or use a dummy mesh and material to ensure the ```<texture>``` elements are processed and then use those. The [ssao-pass.js](https://github.com/xml3d/xml3d.js/blob/master/src/renderer/webgl/render-passes/ssao-pass.js) file has an example of a texture that's loaded manually, in this case the src is a base64 data string but the idea would be exactly the same if it were an external image.
