### ISSUE TITLE
specification xml3d

### ISSUE THREAD

**Issue by juceo** [xml3d/xml3d.js#198]
I understand that the project has been discontinued. But I have several projects developed in xml3d. I can't find the specifications anywhere and the page where I was is no longer available. Is it possible that they can publish these specifications on github? At least the last two. Is there any other place where I can find them.

**Comment by csvurt** [comment]
Hi juceo,

the specification document is also here in the repository:

https://github.com/xml3d/xml3d.js/tree/master/spec

The easiest way to access it would be to clone the repo and open it locally. The specification for older versions can be accessed by switching to the appropriate tag in the repository, eg `git checkout 5.1.4` for v5.1.4
