### ISSUE TITLE
Firefox can't handle relative refs in external remote files.

### ISSUE THREAD

**Issue by A-K** [xml3d/xml3d.js#26]
Chrome and Firefox behaves differently when loading .xml files from remote server using remote refs in meshes and shaders. For example appending xml3d element with this group:

```
<group id = "someId" shader="https://someUrl/someModel.xml#material">
        <mesh src="https://someUrl/someModel.xml#someMesh" type="triangles"/>
 </group>
```

with the someMesh part in the someModel.xml file:

```
<data id="someMesh">
    <float3 name="position">
    ...           
    </float3>
    <float3 name="normal">
    ...           
    </float3>
    <float2 name="texcoord">
    ...          
    </float2>
</data>
<data id="subMesh">
    <data src="#someMesh"/>
        <int name="index">
        ...       
        </int>
</data>
```

works fine in Chrome, but fails when using Firefox. Everything works fine when the ref in subMesh is absolute:

 ```
<data src="https://someUrl/someModel.xml#someMesh"/>
```

Same thing happens when the shader has a texture which has a relative reference to some image.

**Comment by csvurt** [comment]
This seems to be working properly in 4.8 so I'm going to close this issue.
