### ISSUE TITLE
getBoundingBox not in local space

### ISSUE THREAD

**Issue by simpae** [xml3d/xml3d.js#30]
According to the specification <code>getBoundingBox</code> always returns the bounding box of the element in local space.
However, calling <code>getBoundingBox</code> on a group element returns a bounding box with values that are obviously in world space.

**Comment by csvurt** [comment]
So the old getBoundingBox function was pretty confusing, it would return boxes in world space for group nodes and local space for mesh nodes. For consistency this function has been split up into getLocalBoundingBox and getWorldBoundingBox, similar to the get*Matrix functions. Both these functions are available on xml3d, group, mesh and model nodes. 

getBoundingBox is now deprecated and will be removed in a future version, until then it follows the old (confusing) behavior of returning world space boxes on group nodes and local space boxes on mesh or model nodes.
