### ISSUE TITLE
"visible" attribute in the <group> element is not taken into account

### ISSUE THREAD

**Issue by rryk** [xml3d/xml3d.js#34]
It is not parsed when new groups are dynamically added or when it is dynamically set. I didn't check if it's correctly handled when an entity is already present in the scene.

After executing either this:

```
groupNodeInScene.setAttribute("visible", "false");
```

or this:

```
var newGroupNode = XML3D.createElement("group");
newGroupNode.appendChild(someMeshWithGeometry);
newGroupNode.setAttribute("visible", "false");
xml3dRootElement.appendChild(newGroupNode);
```

the added group is still visible.

**Comment by csvurt** [comment]
This seems to be working properly in the mean time. I've added another set of tests since I couldn't find any existing ones for cases where the group or mesh is set invisible before it's inserted into the DOM.
