### ISSUE TITLE
Drawing complex meshes is not supported

### ISSUE THREAD

**Issue by K1ll3rF0x** [xml3d/xml3d.js#40]
We have a case where a triangulated plane containing a quite large amount of vertices is created and it should be rendered with XML3D.js. 

However, because WebGL cannot handle so many vertices in a single draw call and XML3D seems to try to draw the whole mesh at once, the drawing will fail. One solution would automatically splitting the mesh  in smaller chunks of max 65535 vertices and then drawing the chunks one by one.

I checked out the code in mesh.js and it seems that you have sketched some code there related to segmented meshes, but it seems unfinished. It would be nice if you could finish this feature so we can render larger meshes with XML3D.js more effortlessly.

**Comment by ksons** [comment]
Fixed in 4.8
