### ISSUE TITLE
Handlers within XML3D stop 'DOMNodeInserted' and 'DOMNodeRemoved' from propagating further.

### ISSUE THREAD

**Issue by cvetan5** [xml3d/xml3d.js#48]
As I had been browsing the source code, I found this issue is already documented [here](https://github.com/xml3d/xml3d.js/blob/master/src/interface/elements.js#L49), so I thought it would be good if I put it in the issue tracker also. 

Currently it is not possible to listen to `DOMNodeInserted` and `DOMNodeRemoved` on a single XML3D element, for example as in my case, listen to the node changes (adding / removing of children) of a `<group>` element.

**Comment by ksons** [comment]
We use MutationObservers now, so this issues schould be fixed. Old style DOM monitoring will be removed with #95
