### ISSUE TITLE
Assetmesh, multiple includes, separator?

### ISSUE THREAD

**Issue by l337r007** [xml3d/xml3d.js#86]
https://github.com/xml3d/xml3d.js/wiki/Assets-and-Model says
```
It's possible to refer multiple <assetdata> entries by writing space separated names within includes.
```
but the example above says
```
<assetmesh includes="base1, base3" ></assetmesh>
```
Which one is correct, then? Not that I would want to use it (then I could've just determined experimentally and updated the wiki myself), I just stumbled across this inconsistency while reading the docs.

**Comment by ksons** [comment]
Includes are comma-separated. I fixed the documentation in the Wiki. Thanks for reporting!

Impl:
https://github.com/xml3d/xml3d.js/blob/master/src/data/adapter/asset.js#L187
