### ISSUE TITLE
Performance issue using animated assets

### ISSUE THREAD

**Issue by stlemme** [xml3d/xml3d.js#87]
When using something like
```html
<transform rotation="0 -0.9322087168693542 -0.36192089319229126 1.1212045627989415" translation="4.156185150146484 -3.1172001361846924 7.501348495483398" scale="0.5 0.5 0.5" id="ship_tf0"></transform>
<model visible="true" transform="#ship_tf0" src="assets/spaceship.xml#asset"></model>
```
and updating the ```rotation``` and ```translation``` attribute once per frame for animation purposes, it causes the invalidation of the whole asset, which ultimately results in a re-computation of the mesh's bbox.

![xml3d-asset-performance](https://cloud.githubusercontent.com/assets/4638670/5679529/fd0e3e82-9800-11e4-8157-ba46bf95e84d.jpg)

**Comment by csvurt** [comment]
The asset won't be invalidated when changing the transform of the model tag so performance should be back to normal now. The fix will be in release 4.9.
