### ISSUE TITLE
Feature: Referencing external xflow operators by uri

### ISSUE THREAD

**Issue by stlemme** [xml3d/xml3d.js#89]
When delivering assets (e.g. as a webservice), these assets can include data flows, which are referenced by uri. Thus, the same webservice can deliver the respective data flows.

These dataflows internally rely on xflow operators, which are referenced by name. Those names are predefined and must be known by the client application.

Hence, it is not possible for a webservice to deliver assets using arbitrary data-flow processing (e.g. domain specific). As workaround it is required that the client application imports a script file with the operator definitions first before using the actual webservice. Moreover, this script file might be implementation-specific rather than API-specific.

**Comment by csvurt** [comment]
This feature is now on the develop branch with commit 86820b914d821145352b746f418f216cb02a694a and will be included in the 4.9 release. You can find the [documentation here.](https://github.com/xml3d/xml3d.js/wiki/External-resources)
