### ISSUE TITLE
Event attributes trigger event twice in HTML encoding

### ISSUE THREAD

**Issue by ksons** [xml3d/xml3d.js#92]
Using eventattributes such as

```html
  <mesh src="teapot.json" onclick="console.log('Teapot');"></mesh>
```

trigger twice. This affects only HTML encoding and event attributes. Using ```addEventListener``` or the same scene in XHTML are not concerned.

**Comment by csvurt** [comment]
I've added checks to the mouse event attributes polyfill that will prevent it from adding a second event listener to the element in HTML documents.
